-- 1. SENSORS TABLE: Tracks physical edge devices deployed in the infrastructure
CREATE TABLE sensors (
    sensor_id VARCHAR(50) PRIMARY KEY,
    sensor_name VARCHAR(100) NOT NULL,
    sensor_type VARCHAR(50) NOT NULL,       -- e.g., 'TEMPERATURE', 'POWER_GRID', 'PROXIMITY'
    location_zone VARCHAR(50) NOT NULL,     -- e.g., 'ZONE_A', 'SERVER_ROOM_1'
    status VARCHAR(20) DEFAULT 'ACTIVE',    -- ACTIVE, MAINTENANCE, OFFLINE
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. SENSOR DATA LOGS TABLE: High-frequency storage for incoming MQTT telemetry data
CREATE TABLE sensor_data_logs (
    log_id BIGSERIAL PRIMARY KEY,
    sensor_id VARCHAR(50) REFERENCES sensors(sensor_id) ON DELETE CASCADE,
    reading_value NUMERIC(10, 2) NOT NULL,
    recorded_at TIMESTAMP NOT NULL          -- Timestamp generated by the edge node
);

-- 3. SYSTEM ALERTS TABLE: Tracks anomalies processed by the Java business logic
CREATE TABLE system_alerts (
    alert_id SERIAL PRIMARY KEY,
    sensor_id VARCHAR(50) REFERENCES sensors(sensor_id) ON DELETE CASCADE,
    alert_level VARCHAR(20) NOT NULL,       -- INFO, WARNING, CRITICAL
    alert_message TEXT NOT NULL,
    is_resolved BOOLEAN DEFAULT FALSE,
    triggered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);